---
- hosts: windows_update
  gather_facts: no
  vars_files:
    - /home/sysadmin/ansible/vault.yml
  tasks:
  - name: Upgrade installed packages
    win_chocolatey:
      name: all
      state: latest
  - name: Update Windows  
    ansible.windows.win_updates:
      category_names: '*'
      reject_list:
      - Microsoft Silverlight
      reboot: no
  - name: Copy Forti.exe From Share
    win_shell: Copy-Item \\data.azurestandard.com\it\ansible\forti.exe c:\temp\bootstrap_files\forti.exe
    become: yes
    become_method: runas
    become_user: azurestandard.com\admin
  - name: Copy Chronical.exe From Share
    win_shell: Copy-Item \\data.azurestandard.com\\it\\ansible\\Chronicall_4_2_10e.exe c:\temp\bootstrap_files\Chronicall_4_2_10e.exe
    become: yes
    become_method: runas
    become_user: azurestandard.com\admin
  - name: Copy bootstap_files directory to temp folder
    ansible.windows.win_copy:
      src: /home/sysadmin/ansible/files/bootstrap_files/exe_update.ps1
      dest: C:\Temp\bootstrap_files\exe_update.ps1
  - name: Run Script to update forti and chronicall if they are installed already
    win_shell: c:\temp\bootstrap_files\exe_update.ps1
    ignore_errors: yes
