- name: install mariaDB package for Ubuntu
  tags: ubuntu,db,mariaDB
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: install mariaDB package for CentOS
  tags: centos,mariadb,db
  dnf:
    name: mariadb
    state: latest
  when: ansible_distribution == "CentOS"
