---
- hosts: new_windows
  gather_facts: no
  tasks:
  - name: Copy a single file
    ansible.windows.win_copy:
      src: /home/sysadmin/ansible_test/files/2020-DeCrapifyandFirstSetup.ps1
      dest: C:\Temp\
  - name: Intall chocolatey on windows
    win_chocolatey: name=procexp state=present
  - name: Install packages
    win_chocolatey: 
      name:
      - googlechrome
      - 7zip
      - foxitreader
      state: present
