---
- hosts: zt_windows:zt_windows_fix 
  gather_facts: false
  vars_files:
  - /home/sysadmin/ansible/vault/vault.yml
  - /home/sysadmin/ansible/vault/local.yml
#  pre_tasks:
#    - include_vars: ../vault/vault.yml
  tasks: 
    - name: Change priority Choco repository
      win_chocolatey_source:
        name: chocolatey
        state: present
        priority: 2
        source: https://community.chocolatey.org/api/v2/

    - name: Add AzureChoco repository
      win_chocolatey_source:
        name: AzureChoco
        state: present
        priority: 1
        source: \\data.azurestandard.com\shared$\chocolatey\
        ignore_errors: yes

    - name: Add AzureZTChoco repository
      win_chocolatey_source:
        name: AzureZTChoco
        state: present
        priority: 1
        source: \\10.211.0.5\shared$\chocolatey\
