---
- hosts: new_windows
  gather_facts: false
  vars_files:
  - /home/sysadmin/ansible/vault/vault.yml
  - /home/sysadmin/ansible/vault/local.yml
  pre_tasks:
    - include_vars: ../vault/vault.yml
  tasks: 
    - name: Change the hostname
      ansible.windows.win_hostname:
        name: "{{ inventory_hostname_short }}"
      register: pc_rename

    - name: Reboot when required
      win_reboot:
      when: pc_rename.reboot_required

    - name: Join PC to Domain
      ansible.windows.win_domain_membership:
        dns_domain_name: AzureStandard.com
        domain_admin_user: admin@azurestandard.com
        domain_admin_password: "{{ win_password }}"
        hostname: "{{ inventory_hostname_short }}"
        state: domain
      register: domain_join
      throttle: 1

    - name: Reboot when required
      win_reboot:
      when: domain_join.reboot_required
