---
- hosts: windows_test
  ignore_errors: yes
  gather_facts: no
  vars_files:
    - /home/sysadmin/ansible/vault/vault.yml
    - /home/sysadmin/ansible/vault/local.yml
  tasks:
  - name: win_ping Ansible Playbook
    win_ping:

  - name: Ensure user ansible is present
    ansible.windows.win_user:
      name: ansible
      password: fGtew456GcxsHc 
      state: present
      groups:
        - Administrators
        - Remote Management Users
      account_disabled: false
