---

- name: Basic Setup for Switch
  hosts: switch

  gather_facts: False
  ignore_errors: yes

  vars_files:
  - /home/sysadmin/ansible/vault.yml
  - /home/sysadmin/ansible/local.yml
  become: yes
  become_user: root
#  ansible_user: sysadmin
#  ansible_password: "{{ win_password }}"


  tasks:

    - name: Create VLAN 2
      ios_vlan:
        vlan_id: 2
        name: WISP_2
        state: present


    - name: Create VLAN 4
      ios_vlan:
        vlan_id: 4
        name: WISP_HARD_WIRED
        state: present

    - name: Create VLAN 5
      ios_vlan:
        vlan_id: 5
        name: WISP_MORO_WEST
        state: present

    - name: Create VLAN 6
      ios_vlan:
        vlan_id: 6
        name: WISP_DUFUR
        state: present

    - name: Create VLAN 8
      ios_vlan:
        vlan_id: 8
        name: WISP_MORO_SOUTH
        state: present

    - name: Create VLAN 9
      ios_vlan:
        vlan_id: 9
        name: MNG
        state: present

    - name: Create VLAN 16
      ios_vlan:
        vlan_id: 16
        name: PITTOCK
        state: present

    - name: Create VLAN 17
      ios_vlan:
        vlan_id: 17
        name: DCC
        state: present

    - name: Create VLAN 18
      ios_vlan:
        vlan_id: 18
        name: FARM
        state: present

    - name: Create VLAN 19
      ios_vlan:
        vlan_id: 19
        name: MWH
        state: present

    - name: Create VLAN 37
      ios_vlan:
        vlan_id: 37
        name: CORP_SERVER
        state: present

    - name: Create VLAN 38
      ios_vlan:
        vlan_id: 38
        name: WISP_APP_SERVERS
        state: present

    - name: Create VLAN 39
      ios_vlan:
        vlan_id: 39
        name: PROTECTED_SERVERS
        state: present

    - name: Create VLAN 41
      ios_vlan:
        vlan_id: 41
        name: VM_MANAGE
        state: present

    - name: Create VLAN 42
      ios_vlan:
        vlan_id: 42
        name: AUTOMATION
        state: present

    - name: Create VLAN 44
      ios_vlan:
        vlan_id: 44
        name: ESCi_NFS
        state: present

    - name: Create VLAN 46
      ios_vlan:
        vlan_id: 46
        name: INTERVM
        state: present

    - name: Create VLAN 47
      ios_vlan:
        vlan_id: 47
        name: RECOVERYPOINT_REP
        state: present

    - name: Create VLAN 52
      ios_vlan:
        vlan_id: 52
        name: MORO_CAMERAS
        state: present

    - name: Create VLAN 53
      ios_vlan:
        vlan_id: 53
        name: MILL_CAMERAS

    - name: Create VLAN 99
      ios_vlan:
        vlan_id: 99
        name: NETWORK_MANAGE
        state: present

    - name: Create VLAN 100
      ios_vlan:
        vlan_id: 100
        name: WIRELESS_PRINTERS
        state: present

    - name: Create VLAN 116
      ios_vlan:
        vlan_id: 116
        name: JUNIPER_VPN
        state: present

    - name: Create VLAN 120
      ios_vlan:
        vlan_id: 120
        name: UBIQUITI_SETUP
        state: present

    - name: Create VLAN 160
      ios_vlan:
        vlan_id: 160
        name: SERVER_DMZ
        state: present

    - name: Create VLAN 162
      ios_vlan:
        vlan_id: 162
        name: INTERROUTER_MORO-ZT
        state: present

    - name: Create VLAN 191
      ios_vlan:
        vlan_id: 191
        name: MORO_GUEST
        state: present

    - name: Create VLAN 199
      ios_vlan:
        vlan_id: 199
        name: PHONE_CONFIG
        state: present

    - name: Create VLAN 201
      ios_vlan:
        vlan_id: 201
        name: MORO-DUFUR
        state: present

    - name: Create VLAN 202
      ios_vlan:
        vlan_id: 202
        name: FARM-DUFUR

    - name: Create VLAN 203
      ios_vlan:
        vlan_id: 203
        name: FARM-PITTOCK
        state: present

    - name: Create VLAN 204
      ios_vlan:
        vlan_id: 204
        name: MORO-PITTOCK
        state: present

    - name: Create VLAN 205
      ios_vlan:
        vlan_id: 205
        name: MORO-FARM
        state: present

    - name: Create VLAN 206
      ios_vlan:
        vlan_id: 206
        name: DUFUR-PITTOCK
        state: present

    - name: Create VLAN 210
      ios_vlan:
        vlan_id: 210
        name: LSN
        state: present

    - name: Create VLAN 450
      ios_vlan:
        vlan_id: 450
        name: WISP450
        state: present

    - name: Create VLAN 453
      ios_vlan:
        vlan_id: 453
        name: VLAN453
        state: present

    - name: Create VLAN 802
      ios_vlan:
        vlan_id: 802
        name: VLAN802
        state: present

    - name: Create VLAN 806
      ios_vlan:
        vlan_id: 806
        name: VLAN806
        state: present

    - name: Create VLAN 807
      ios_vlan:
        vlan_id: 807
        name: VLAN807
        state: present

    - name: Create VLAN 808
      ios_vlan:
        vlan_id: 808
        name: VLAN808
        state: present

    - name: Create VLAN 812
      ios_vlan:
        vlan_id: 812
        name: VLAN812
        state: present

    - name: Create VLAN 999
      ios_vlan:
        vlan_id: 999
        name: VLAN999
        state: present


    - name: Create VLAN 1601
      ios_vlan:
        vlan_id: 1601
        name: MWH_PHONE
        state: present

    - name: Create VLAN 1602
      ios_vlan:
        vlan_id: 1602
        name: FARM_PHONE
        state: present

    - name: Create VLAN 1603
      ios_vlan:
        vlan_id: 1603
        name: DCC_PHONE
        state: present

    - name: Create VLAN 2004
      ios_vlan:
        vlan_id: 2004
        name: MWH_OFFICE
        state: present

    - name: Create VLAN 2008
      ios_vlan:
        vlan_id: 2008
        name: MWH_PRODUCTION
        state: present

    - name: Create VLAN 2010
      ios_vlan:
        vlan_id: 2010
        name: IMAGING
        state: present

