---
- hosts: zt_me
  ignore_errors: yes
  gather_facts: no
  vars_files:
    - /home/sysadmin/ansible/vault.yml
    - /home/sysadmin/ansible/local.yml
      
  tasks:
  - name: Use Simple auth over LDAPS
    set_fact:
      ansible_password: "{{ lookup('community.windows.laps_password', 'hplt-164',
                                   domain='vsvr20-dc.azurestandard.com',
                                   auth='simple',
                                   scheme='ldaps',
                                   username='admin@AZURESTANDARD.COM',
                                   password='{{ win_password }}') }}"
                                  
