---
#### ZT hosts section ####

- hosts: zt
  gather_facts: no
  ignore_errors: yes
  vars_files:
    - /home/sysadmin/ansible/vault/vault.yml
    - /home/sysadmin/ansible/vault/local.yml
  tasks:

#  - name: Add AzureZTChoco repository
#    win_chocolatey_source:
#      name: AzureZTChoco
#      state: present
#      priority: 1
#      source: \\10.211.0.5\shared$\chocolatey\
#      source_username: azurestandard.com\ansible
#      source_password: "{{ local_password }}"


  - name: Update Select Choco Packages
    win_chocolatey:
      name: '{{ item }}'
      state: latest
    loop:
    - googlechrome
    - 7zip
    - foxitreader
    - notepadplusplus
    - zoom
    - zerotier-one
#  - name: Copy bootstap_files directory to temp folder
#    ansible.windows.win_copy:
#      src: /home/sysadmin/ansible/files/bootstrap_files/
#      dest: C:\Temp\bootstrap_files\
