---
vars_files:
- /home/sysadmin/ansible/vault/vault.yml
- /home/sysadmin/ansible/vault/local.yml
- /home/sysadmin/ansible/vault/edgeos.yml

ansible_password_file: /home/sysadmin/ansible/vault/edgeos.yml
ansible_network_os: edgeos
become_method: enable
#ansible_user: azuresysadmin
ansible_user: ubnt
ansible_password: "{{ edgeos }}"
ansible_become_password: "{{ edgeos }}"
ansible_connection: network_cli
wp_variable: "{{ egdeos }}"
#ansible_become_user: azuresysadmin
ansible_become_user: ubnt

